### ISSUE TITLE
Upgrade from 9.1.2 fails

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/splunk-ansible#778]
```
TASK [splunk_common : Start Splunk via CLI] ************************************
fatal: [localhost]: FAILED! => {
    "attempts": 5,
    "changed": false,
    "cmd": [
        "/opt/splunk/bin/splunk",
        "start",
        "--accept-license",
        "--answer-yes",
        "--no-prompt"
    ],
    "delta": "0:00:00.525614",
    "end": "2024-01-29 11:50:32.775842",
    "rc": 1,
    "start": "2024-01-29 11:50:32.250228"
}

STDOUT:


This appears to be an upgrade of Splunk.
--------------------------------------------------------------------------------)

Splunk has detected an older version of Splunk installed on this machine. To
finish upgrading to the new version, Splunk's installer will automatically
update and alter your current configuration files. Deprecated configuration
files will be renamed with a .deprecated extension.

You can choose to preview the changes that will be made to your configuration
files before proceeding with the migration and upgrade:

If you want to migrate and upgrade without previewing the changes that will be
made to your existing configuration files, choose 'y'.
If you want to see what changes will be made before you proceed with the
upgrade, choose 'n'.


Perform migration and upgrade without previewing configuration changes? [y/n] y

Migrating to:
VERSION=9.1.3
BUILD=d95b3299fa65
PRODUCT=splunk
PLATFORM=Linux-x86_64


STDERR:


-- Migration information is being logged to '/opt/splunk/var/log/splunk/migration.log.2024-01-29.11-50-32' --
Traceback (most recent call last):
  File "/opt/splunk/lib/python3.7/site-packages/splunk/clilib/cli.py", line 38, in <module>
    import splunk.auth as auth
  File "/opt/splunk/lib/python3.7/site-packages/splunk/auth.py", line 9, in <module>
    import splunk.entity as en
  File "/opt/splunk/lib/python3.7/site-packages/splunk/entity.py", line 12, in <module>
    import splunk.rest as rest
  File "/opt/splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 32, in <module>
    import splunk.ssl_context
  File "/opt/splunk/lib/python3.7/site-packages/splunk/ssl_context.py", line 35, in <module>
    import splunk.mining.dcutils as dcu
  File "/opt/splunk/lib/python3.7/site-packages/splunk/mining/dcutils.py", line 50, in <module>
    scannedLogLevel = config_cp.get('python', 'splunk')
  File "/opt/splunk/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/opt/splunk/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'python'


MSG:

non-zero return code
```

/opt/splunk/var/log/splunk/migration.log.2024-01-29.11-50-32 has only:
```
cat /opt/splunk/var/log/splunk/migration.log.2024-01-29.11-50-32

Migrating to:
VERSION=9.1.3
BUILD=d95b3299fa65
PRODUCT=splunk
PLATFORM=Linux-x86_64
```

**Comment by jmeixensperger** [comment]
Can you confirm if this is still an issue? I was unable to reproduce with the following steps:

1. launch a container with splunk/splunk:9.1.2 (build: b6b9c8185839)
2. set splunk build location in ansible inventory defaults with 9.1.3 (build: d95b3299fa65)
3. trigger ansible provisioning

**Comment by yaroslav-nakonechnikov** [comment]
as there passed a lot of time, this ticket is not relevant anymore.
